-- MySQL Script generated by MySQL Workbench
-- Mon Oct 31 21:08:33 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema trans_comp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema trans_comp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trans_comp` DEFAULT CHARACTER SET utf8 ;
USE `trans_comp` ;

-- -----------------------------------------------------
-- Table `trans_comp`.`Drivers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trans_comp`.`Drivers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `driving_experience` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trans_comp`.`Operator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trans_comp`.`Operator` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name_operator` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trans_comp`.`autopark`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trans_comp`.`autopark` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(255) NOT NULL,
  `mileage` INT NOT NULL,
  `tonnage` INT NOT NULL,
  `Operator_id` INT NOT NULL,
  `Drivers_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_autopark_Drivers_idx` (`Drivers_id` ASC) VISIBLE,
  INDEX `fk_autopark_Operator1_idx` (`Operator_id` ASC) VISIBLE,
  CONSTRAINT `fk_autopark_Drivers`
    FOREIGN KEY (`Drivers_id`)
    REFERENCES `trans_comp`.`Drivers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_autopark_Operator1`
    FOREIGN KEY (`Operator_id`)
    REFERENCES `trans_comp`.`Operator` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trans_comp`.`trip_ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trans_comp`.`trip_ticket` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `town` VARCHAR(255) NOT NULL,
  `stopover` VARCHAR(255) NOT NULL,
  `Drivers_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_trip_ticket_Drivers1_idx` (`Drivers_id` ASC) VISIBLE,
  CONSTRAINT `fk_trip_ticket_Drivers1`
    FOREIGN KEY (`Drivers_id`)
    REFERENCES `trans_comp`.`Drivers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trans_comp`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trans_comp`.`client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `client_name` VARCHAR(255) NOT NULL,
  `adress_client` VARCHAR(255) NOT NULL,
  `Operator_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_client_Operator1_idx` (`Operator_id` ASC) VISIBLE,
  CONSTRAINT `fk_client_Operator1`
    FOREIGN KEY (`Operator_id`)
    REFERENCES `trans_comp`.`Operator` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
